package com.checongbinh.Nexflix.mapper;

import com.checongbinh.Nexflix.model.User;
import com.checongbinh.Nexflix.model.UserExample;
import com.checongbinh.Nexflix.model.UserKey;
import com.checongbinh.Nexflix.model.UserWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 22 07:49:29 ICT 2024
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 22 07:49:29 ICT 2024
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 22 07:49:29 ICT 2024
	 */
	int insert(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 22 07:49:29 ICT 2024
	 */
	int insertSelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 22 07:49:29 ICT 2024
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 22 07:49:29 ICT 2024
	 */
	int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Apr 22 07:49:29 ICT 2024
	 */
	int updateByExample(@Param("row") User row, @Param("example") UserExample example);
}